### ISSUE TITLE
the logic of pie chart Disk Usage is incorrect

### ISSUE THREAD

**Issue by timmyz** [citahub/cita-monitor#87]
each item of Metrics in a pie chart means one part of the whole pie.
so if here A means the total size of current node data used, while B means the disk size of current node, the percentages of them will be meaningless.

i think B should be
```
$NodeDisk-(Node_Get_DirInfo_TotalFileSize{job="$job",instance="$node:$port"} * 1024)
```
and the label of it should be something like `unused disk`.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/795528/57921163-4acca600-78cf-11e9-923d-46ba0585a4a1.png">

**Comment by rainchen** [comment]
You're right. 
This view is designed to present the NodeDirSize vs TotalDiskSize so that we can know the percentage that the node used. 
So that there should be 3 parts:
* NodeDirSize
* OtherUsed
* Available

`TotalDiskSize = NodeDirSize + OtherUsed + Available`

![Screen Shot 2019-05-17 at 7 00 19 PM](https://user-images.githubusercontent.com/71397/57923923-26c09300-78d6-11e9-91c9-dea2763c324a.png)

We need to fix this.
